global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'backend'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:4000']

  - job_name: 'client'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:5000']
